[pytest]
filterwarnings =
    ignore::DeprecationWarning:nemoguardrails\.
    ignore::DeprecationWarning:langchain_community\.
    ignore::DeprecationWarning:langchain_core\.
    ignore:There is no current event loop:DeprecationWarning:nemoguardrails\.utils